# SAP FI synthetic SQLite schema ------------------------------------------------
# The goal is SAP-style analytics data, not a byte-for-byte SAP replica.

create_db <- function(db_path = "data/sap_fi.sqlite") {
  dir.create(dirname(db_path), recursive = TRUE, showWarnings = FALSE)
  con <- DBI::dbConnect(RSQLite::SQLite(), db_path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)

  DBI::dbExecute(con, "PRAGMA foreign_keys = ON;")

  schema_sql <- "
CREATE TABLE IF NOT EXISTS T001 (
  MANDT TEXT NOT NULL,
  BUKRS TEXT PRIMARY KEY,
  BUTXT TEXT NOT NULL,
  LAND1 TEXT NOT NULL,
  WAERS TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS KNA1 (
  MANDT TEXT NOT NULL,
  KUNNR TEXT PRIMARY KEY,
  NAME1 TEXT NOT NULL,
  LAND1 TEXT NOT NULL,
  ORT01 TEXT,
  PSTLZ TEXT,
  STRAS TEXT,
  STCD1 TEXT,
  KTOKD TEXT NOT NULL,
  ERDAT TEXT NOT NULL,
  LOEVM TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS KNB1 (
  MANDT TEXT NOT NULL,
  KUNNR TEXT NOT NULL,
  BUKRS TEXT NOT NULL,
  AKONT TEXT NOT NULL,
  ZTERM TEXT NOT NULL,
  ZWELS TEXT,
  FDGRV TEXT,
  PRIMARY KEY (KUNNR, BUKRS),
  FOREIGN KEY (KUNNR) REFERENCES KNA1(KUNNR),
  FOREIGN KEY (BUKRS) REFERENCES T001(BUKRS)
);

CREATE TABLE IF NOT EXISTS LFA1 (
  MANDT TEXT NOT NULL,
  LIFNR TEXT PRIMARY KEY,
  NAME1 TEXT NOT NULL,
  LAND1 TEXT NOT NULL,
  ORT01 TEXT,
  PSTLZ TEXT,
  STRAS TEXT,
  STCD1 TEXT,
  KTOKK TEXT NOT NULL,
  ERDAT TEXT NOT NULL,
  LOEVM TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS LFB1 (
  MANDT TEXT NOT NULL,
  LIFNR TEXT NOT NULL,
  BUKRS TEXT NOT NULL,
  AKONT TEXT NOT NULL,
  ZTERM TEXT NOT NULL,
  ZWELS TEXT,
  FDGRV TEXT,
  PRIMARY KEY (LIFNR, BUKRS),
  FOREIGN KEY (LIFNR) REFERENCES LFA1(LIFNR),
  FOREIGN KEY (BUKRS) REFERENCES T001(BUKRS)
);

CREATE TABLE IF NOT EXISTS SKA1 (
  MANDT TEXT NOT NULL,
  KTOPL TEXT NOT NULL,
  SAKNR TEXT NOT NULL,
  TXT50 TEXT NOT NULL,
  GLACCOUNT_TYPE TEXT NOT NULL,
  XBILK TEXT DEFAULT '',
  PRIMARY KEY (KTOPL, SAKNR)
);

CREATE TABLE IF NOT EXISTS SKB1 (
  MANDT TEXT NOT NULL,
  BUKRS TEXT NOT NULL,
  SAKNR TEXT NOT NULL,
  WAERS TEXT,
  XINTB TEXT DEFAULT '',
  FSTAG TEXT,
  PRIMARY KEY (BUKRS, SAKNR),
  FOREIGN KEY (BUKRS) REFERENCES T001(BUKRS)
);

CREATE TABLE IF NOT EXISTS BKPF (
  MANDT TEXT NOT NULL,
  BUKRS TEXT NOT NULL,
  BELNR TEXT NOT NULL,
  GJAHR INTEGER NOT NULL,
  BLART TEXT NOT NULL,
  BLDAT TEXT NOT NULL,
  BUDAT TEXT NOT NULL,
  MONAT INTEGER NOT NULL,
  CPUDT TEXT NOT NULL,
  CPUTM TEXT NOT NULL,
  WAERS TEXT NOT NULL,
  KURSF REAL DEFAULT 1,
  XBLNR TEXT,
  BKTXT TEXT,
  USNAM TEXT NOT NULL,
  TCODE TEXT,
  PRIMARY KEY (BUKRS, BELNR, GJAHR),
  FOREIGN KEY (BUKRS) REFERENCES T001(BUKRS)
);

CREATE TABLE IF NOT EXISTS BSEG (
  MANDT TEXT NOT NULL,
  BUKRS TEXT NOT NULL,
  BELNR TEXT NOT NULL,
  GJAHR INTEGER NOT NULL,
  BUZEI INTEGER NOT NULL,
  BSCHL TEXT NOT NULL,
  KOART TEXT NOT NULL,
  SHKZG TEXT NOT NULL,
  DMBTR REAL NOT NULL,
  WRBTR REAL NOT NULL,
  WAERS TEXT NOT NULL,
  HKONT TEXT,
  KUNNR TEXT,
  LIFNR TEXT,
  SGTXT TEXT,
  ZUONR TEXT,
  AUGBL TEXT,
  AUGDT TEXT,
  ZTERM TEXT,
  ZFBDT TEXT,
  ZBD1T INTEGER,
  PRCTR TEXT,
  KOSTL TEXT,
  MWSKZ TEXT,
  PRIMARY KEY (BUKRS, BELNR, GJAHR, BUZEI),
  FOREIGN KEY (BUKRS, BELNR, GJAHR) REFERENCES BKPF(BUKRS, BELNR, GJAHR)
);

CREATE TABLE IF NOT EXISTS BSID AS SELECT * FROM BSEG WHERE 0; -- AR open items
CREATE TABLE IF NOT EXISTS BSAD AS SELECT * FROM BSEG WHERE 0; -- AR cleared items
CREATE TABLE IF NOT EXISTS BSIK AS SELECT * FROM BSEG WHERE 0; -- AP open items
CREATE TABLE IF NOT EXISTS BSAK AS SELECT * FROM BSEG WHERE 0; -- AP cleared items
CREATE TABLE IF NOT EXISTS BSIS AS SELECT * FROM BSEG WHERE 0; -- GL open items
CREATE TABLE IF NOT EXISTS BSAS AS SELECT * FROM BSEG WHERE 0; -- GL cleared items

CREATE TABLE IF NOT EXISTS ACDOCA (
  RCLNT TEXT NOT NULL,
  RLDNR TEXT NOT NULL,
  RBUKRS TEXT NOT NULL,
  GJAHR INTEGER NOT NULL,
  BELNR TEXT NOT NULL,
  DOCLN INTEGER NOT NULL,
  RACCT TEXT,
  KOART TEXT,
  DRCRK TEXT NOT NULL,
  HSL REAL NOT NULL,
  WSL REAL NOT NULL,
  RHCUR TEXT NOT NULL,
  RWCUR TEXT NOT NULL,
  BUDAT TEXT NOT NULL,
  BLART TEXT NOT NULL,
  SGTXT TEXT,
  PRCTR TEXT,
  RCNTR TEXT,
  KUNNR TEXT,
  LIFNR TEXT,
  PRIMARY KEY (RBUKRS, BELNR, GJAHR, DOCLN)
);

CREATE INDEX IF NOT EXISTS IX_BKPF_BUDAT ON BKPF(BUKRS, BUDAT);
CREATE INDEX IF NOT EXISTS IX_BSEG_ACCOUNT ON BSEG(BUKRS, HKONT, KUNNR, LIFNR);
CREATE INDEX IF NOT EXISTS IX_BSID_CUSTOMER ON BSID(BUKRS, KUNNR, GJAHR);
CREATE INDEX IF NOT EXISTS IX_BSIK_VENDOR ON BSIK(BUKRS, LIFNR, GJAHR);
CREATE INDEX IF NOT EXISTS IX_BSIS_GL ON BSIS(BUKRS, HKONT, GJAHR);
CREATE INDEX IF NOT EXISTS IX_ACDOCA_ACCOUNT ON ACDOCA(RBUKRS, RACCT, BUDAT);
"

  statements <- strsplit(schema_sql, ";", fixed = TRUE)[[1]]
  statements <- trimws(statements)
  statements <- statements[nchar(statements) > 0]

  for (stmt in statements) {
    DBI::dbExecute(con, stmt)
  }

  invisible(db_path)
}
